### ISSUE TITLE
Redirect/re-route to login page

### ISSUE THREAD

**Issue by jasonlaw** [Danangjoyoo/flask-http-middleware#1]
Hi,

I would like to re-route to a login page when failed authentication, may I know how to do that?

Thanks.

**Comment by Danangjoyoo** [comment]
Have you tried to return it with `redirect` ?
```
from flask import redirect
```

**Comment by Danangjoyoo** [comment]
hi @jasonlaw , any updates?

**Comment by Danangjoyoo** [comment]
will mark this as closed ya
