### ISSUE TITLE
MiddlewareManager not compatible with CORS()

### ISSUE THREAD

**Issue by prakharlohumi** [Danangjoyoo/flask-http-middleware#11]
The MiddlewareManager class provided by flask helps executes all the middleware attached to the app.

The CORS class is used to make the app compatible with CORS requests. CORS does this by appending a function to the after_request to the app that is run after all requests. 

The MiddlewareManager provided by flask, however, does not run the post processors.

![Screenshot 2024-06-12 at 12 29 46 AM](https://github.com/Danangjoyoo/flask-http-middleware/assets/35093143/99c79d8d-7feb-44bc-9438-1d4bb9d87c9d)

Note the difference between the if and the else blocks.
1. if a middleware stack is present, then we are returning the response passed through the make_response() function (from the process_request_and_get_response function)
2. If a stack is not present, then we are retuning the response passed through the finalise_request() method. This method is where the after_request functions are executed by flask.

**Comment by Korulag** [comment]
This also affects setting session data in endpoint: after passing through middleware, the session data is lost

**Comment by Korulag** [comment]
@prakharlohumi please try https://github.com/Danangjoyoo/flask-http-middleware/pull/12, maybe it will fix your issues as well

**Comment by Danangjoyoo** [comment]
@prakharlohumi @Korulag I've released the new version `0.4.3` please kindly try it, thanks for the help of the bugfix @Korulag

**Comment by Korulag** [comment]
@Danangjoyoo tested on my deployment, sessions work as expected
