### ISSUE TITLE
MiddlewareManager and ProxyFix

### ISSUE THREAD

**Issue by mariofix** [Danangjoyoo/flask-http-middleware#4]
Hi, I just notices your module and it looks very nicely done.
I have a small issue tough, it doesn't work well with `werkzeug.middleware.proxy_fix.ProxyFix`

```python
app = Flask(__name__)
app.wsgi_app = ProxyFix(app.wsgi_app)
app.wsgi_app = MiddlewareManager(app)
app.wsgi_app.add_middleware(AllowedDomainsMiddleware)
```

ProxyFix get's overwritten every time, and if I add it later, `add_middleware` is not available.

Thanks for any help

**Comment by Danangjoyoo** [comment]
Hi @mariofix , sorry for late response

have you try to put `ProxyFix(app.wsgi_app)` after `MiddlewareManager(app)` ?

something like
```
app = Flask(__name__)
app.wsgi_app = MiddlewareManager(app)
app.wsgi_app = ProxyFix(app.wsgi_app)
app.wsgi_app.add_middleware(AllowedDomainsMiddleware)
```

**Comment by mariofix** [comment]
Thanks for your reply.

If I do this
```python
app = Flask(__name__)
app.wsgi_app = MiddlewareManager(app)
app.wsgi_app = ProxyFix(app.wsgi_app)
app.wsgi_app.add_middleware(AllowedDomainsMiddleware)
```
I get the error `AttributeError: 'ProxyFix' object has no attribute 'add_middleware'`


I just noticed something and manage to get it working with
```python
app = Flask(__name__)
app.wsgi_app = MiddlewareManager(app)
app.wsgi_app.add_middleware(AllowedDomainsMiddleware)
app.wsgi_app = ProxyFix(app.wsgi_app)
```
